clients:
  bar:
    deployment: plus
    services:
      db_proxy:
        DB_HOST: bar_db_host
        DB_NAME: bar_db_name
        DB_PASS: bar_db_pass
        DB_USER: bar_db_user
      ecommerce:
        max_products: 1000
        percent_fee: 5
        site_name: 'Bar Storefront'
      webserver:
        rate_limiter: 1000
        site_name: Bar
        theme: normal
    type: prod
  baz:
    deployment: premium
    services:
      analytics:
        api_key: baz_api_key
        rate_limiter: 100
      db_proxy:
        DB_HOST: baz_db_host
        DB_NAME: baz_db_name
        DB_PASS: baz_db_pass
        DB_USER: baz_db_user
      ecommerce:
        max_products: 3000
        percent_fee: 4
        site_name: 'Baz Storefront'
      webserver:
        rate_limiter: 3000
        site_name: Baz
        theme: material
    type: prod
  foo:
    deployment: free
    services:
      db_proxy:
        DB_HOST: foo_db_host
        DB_NAME: foo_db_name
        DB_PASS: foo_db_pass
        DB_USER: foo_db_user
      webserver:
        rate_limiter: 100
        site_name: Foo
        theme: normal
    type: prod
  qux:
    deployment: enterprise
    services:
      analytics:
        api_key: qux_api_key
        rate_limiter: 200
      crm:
        max_users: 5000
      db_proxy:
        DB_HOST: qux_db_host
        DB_NAME: qux_db_name
        DB_PASS: qux_db_pass
        DB_USER: qux_db_user
      ecommerce:
        max_products: 5000
        percent_fee: 3
        site_name: 'Qux Storefront'
      webserver:
        rate_limiter: 3000
        site_name: Qux
        theme: material
    type: prod
  staging_enterprise:
    deployment: enterprise
    services:
      analytics:
        api_key: staging_enterprise_api_key
        rate_limiter: 200
      crm:
        max_users: 5000
      db_proxy:
        DB_HOST: staging_enterprise_db_host
        DB_NAME: staging_enterprise_db_name
        DB_PASS: staging_enterprise_db_pass
        DB_USER: staging_enterprise_db_user
      ecommerce:
        max_products: 5000
        percent_fee: 3
        site_name: 'Staging Client Enterprise Store'
      webserver:
        rate_limiter: 3000
        site_name: 'Staging Client Enterprise'
        theme: material
    type: staging
  staging_free:
    deployment: free
    services:
      db_proxy:
        DB_HOST: staging_free_db_host
        DB_NAME: staging_free_db_name
        DB_PASS: staging_free_db_pass
        DB_USER: staging_free_db_user
      webserver:
        rate_limiter: 100
        site_name: 'Staging Client Free'
        theme: normal
    type: staging
  staging_plus:
    deployment: plus
    services:
      db_proxy:
        DB_HOST: staging_plus_db_host
        DB_NAME: staging_plus_db_name
        DB_PASS: staging_plus_db_pass
        DB_USER: staging_plus_db_user
      ecommerce:
        max_products: 1000
        percent_fee: 5
        site_name: 'Staging Client Plus Store'
      webserver:
        rate_limiter: 1000
        site_name: 'Staging Client Plus'
        theme: normal
    type: staging
  staging_premium:
    deployment: premium
    services:
      analytics:
        api_key: staging_premium_api_key
        rate_limiter: 100
      db_proxy:
        DB_HOST: staging_premium_db_host
        DB_NAME: staging_premium_db_name
        DB_PASS: staging_premium_db_pass
        DB_USER: staging_premium_db_user
      ecommerce:
        max_products: 3000
        percent_fee: 4
        site_name: 'Staging Client Premium Store'
      webserver:
        rate_limiter: 3000
        site_name: 'Staging Client Premium'
        theme: material
    type: staging
deployments:
  enterprise:
    services:
    - analytics
    - crm
    - db_proxy
    - ecommerce
    - webserver
  free:
    services:
    - db_proxy
    - webserver
  plus:
    services:
    - db_proxy
    - ecommerce
    - webserver
  premium:
    services:
    - analytics
    - db_proxy
    - ecommerce
    - webserver
services:
  analytics:
    registry: rowsheet/analytics
    repository: github.com/rowsheet/analytics
    version_status:
      prod: latest
      stage: latest
    env_var_req:
      api_key: true
      rate_limiter: true
  crm:
    registry: rowsheet/crm
    repository: github.com/rowsheet/crm
    version_status:
      prod: latest
      stage: latest
    env_var_req:
      max_users: true
  db_proxy:
    registry: rowsheet/db_proxy
    repository: github.com/rowsheet/db_proxy
    version_status:
      prod: latest
      stage: latest
    env_var_req:
      DB_HOST: true
      DB_NAME: true
      DB_PASS: true
      DB_USER: true
      TEST_EXTRA: false
  ecommerce:
    registry: rowsheet/ecommerce
    repository: github.com/rowsheet/ecommerce
    version_status:
      prod: latest
      stage: latest
    env_var_req:
      max_products: true
      percent_fee: true
      site_name: true
  webserver:
    registry: rowsheet/webserver
    repository: github.com/rowsheet/webserver
    version_status:
      prod: latest
      stage: latest
    env_var_req:
      rate_limiter: true
      site_name: true
      theme: true
