clients:
  bar:
    deployment: plus
    services:
      db_proxy:
        DB_HOST: bar_db_host
        DB_NAME: bar_db_name
        DB_PASS: bar_db_pass
        DB_USER: bar_db_user
      ecommerce:
        max_products: 1000
        percent_fee: 5
        site_name: 'Bar Storefront'
      webserver:
        rate_limiter: 1000
        site_name: Bar
        theme: normal
    type: prod
  baz:
    deployment: premium
    services:
      analytics:
        api_key: baz_api_key
        rate_limiter: 100
      db_proxy:
        DB_HOST: baz_db_host
        DB_NAME: baz_db_name
        DB_PASS: baz_db_pass
        DB_USER: baz_db_user
      ecommerce:
        max_products: 3000
        percent_fee: 4
        site_name: 'Baz Storefront'
      webserver:
        rate_limiter: 3000
        site_name: Baz
        theme: material
    type: prod
  foo:
    deployment: free
    services:
      db_proxy:
        DB_HOST: foo_db_host
        DB_NAME: foo_db_name
        DB_PASS: foo_db_pass
        DB_USER: foo_db_user
      webserver:
        rate_limiter: 100
        site_name: Foo
        theme: normal
    type: prod
  qux:
    deployment: enterprise
    services:
      analytics:
        api_key: qux_api_key
        rate_limiter: 200
      crm:
        max_users: 5000
      db_proxy:
        DB_HOST: qux_db_host
        DB_NAME: qux_db_name
        DB_PASS: qux_db_pass
        DB_USER: qux_db_user
      ecommerce:
        max_products: 5000
        percent_fee: 3
        site_name: 'Qux Storefront'
      webserver:
        rate_limiter: 3000
        site_name: Qux
        theme: material
    type: prod
  staging_enterprise:
    deployment: enterprise
    services:
      analytics:
        api_key: staging_enterprise_api_key
        rate_limiter: 200
      crm:
        max_users: 5000
      db_proxy:
        DB_HOST: staging_enterprise_db_host
        DB_NAME: staging_enterprise_db_name
        DB_PASS: staging_enterprise_db_pass
        DB_USER: staging_enterprise_db_user
      ecommerce:
        max_products: 5000
        percent_fee: 3
        site_name: 'Staging Client Enterprise Store'
      webserver:
        rate_limiter: 3000
        site_name: 'Staging Client Enterprise'
        theme: material
    type: staging
  staging_free:
    deployment: free
    services:
      db_proxy:
        DB_HOST: staging_free_db_host
        DB_NAME: staging_free_db_name
        DB_PASS: staging_free_db_pass
        DB_USER: staging_free_db_user
      webserver:
        rate_limiter: 100
        site_name: 'Staging Client Free'
        theme: normal
    type: staging
  staging_plus:
    deployment: plus
    services:
      db_proxy:
        DB_HOST: staging_plus_db_host
        DB_NAME: staging_plus_db_name
        DB_PASS: staging_plus_db_pass
        DB_USER: staging_plus_db_user
      ecommerce:
        max_products: 1000
        percent_fee: 5
        site_name: 'Staging Client Plus Store'
      webserver:
        rate_limiter: 1000
        site_name: 'Staging Client Plus'
        theme: normal
    type: staging
  staging_premium:
    deployment: premium
    services:
      analytics:
        api_key: staging_premium_api_key
        rate_limiter: 100
      db_proxy:
        DB_HOST: staging_premium_db_host
        DB_NAME: staging_premium_db_name
        DB_PASS: staging_premium_db_pass
        DB_USER: staging_premium_db_user
      ecommerce:
        max_products: 3000
        percent_fee: 4
        site_name: 'Staging Client Premium Store'
      webserver:
        rate_limiter: 3000
        site_name: 'Staging Client Premium'
        theme: material
    type: staging
deployments:
  enterprise:
    services:
      analytics:
        prod:
          repository: rowsheet/analytics
          tag: latest
        stage:
          repository: rowsheet/analytics
          tag: latest
      crm:
        prod:
          repository: rowsheet/crm
          tag: latest
        stage:
          repository: rowsheet/crm
          tag: latest
      db_proxy:
        prod:
          repository: rowsheet/db_proxy
          tag: latest
        stage:
          repository: rowsheet/db_proxy
          tag: latest
      ecommerce:
        prod:
          repository: rowsheet/ecommerce
          tag: latest
        stage:
          repository: rowsheet/ecommerce
          tag: latest
      webserver:
        prod:
          repository: rowsheet/webserver
          tag: latest
        stage:
          repository: rowsheet/webserver
          tag: latest
  free:
    services:
      db_proxy:
        prod:
          repository: rowsheet/db_proxy
          tag: latest
        stage:
          repository: rowsheet/db_proxy
          tag: latest
      webserver:
        prod:
          repository: rowsheet/webserver
          tag: v0.0.1
        stage:
          repository: rowsheet/webserver
          tag: latest
  plus:
    services:
      db_proxy:
        prod:
          repository: rowsheet/db_proxy
          tag: latest
        stage:
          repository: rowsheet/db_proxy
          tag: v0.0.1
      ecommerce:
        prod:
          repository: rowsheet/ecommerce
          tag: latest
        stage:
          repository: rowsheet/ecommerce
          tag: latest
      webserver:
        prod:
          repository: rowsheet/webserver
          tag: latest
        stage:
          repository: rowsheet/webserver
          tag: latest
  premium:
    services:
      analytics:
        prod:
          repository: rowsheet/analytics
          tag: latest
        stage:
          repository: rowsheet/analytics
          tag: latest
      db_proxy:
        prod:
          repository: rowsheet/db_proxy
          tag: latest
        stage:
          repository: rowsheet/db_proxy
          tag: latest
      ecommerce:
        prod:
          repository: rowsheet/ecommerce
          tag: latest
        stage:
          repository: rowsheet/ecommerce
          tag: latest
      webserver:
        prod:
          repository: rowsheet/webserver
          tag: latest
        stage:
          repository: rowsheet/webserver
          tag: v0.0.2
services:
  analytics:
    api_key: true
    rate_limiter: true
  crm:
    max_users: true
  db_proxy:
    DB_HOST: true
    DB_NAME: true
    DB_PASS: true
    DB_USER: true
    TEST_EXTRA: false
  ecommerce:
    max_products: true
    percent_fee: true
    site_name: true
  webserver:
    rate_limiter: true
    site_name: true
    theme: true
